#!/usr/bin/env python3
"""Build the deterministic, offline AI Shield v2 Naive Bayes model."""

from collections import Counter
import csv
import hashlib
import json
import math
from pathlib import Path
import random
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "research" / "data"
OUT = ROOT / "research" / "v2"
SEED = 20260915
WORD_RE = re.compile(r"[^\W_]", re.UNICODE)


def normalize(value):
    return re.sub(r"\s+", " ", str(value or "").lower()).strip()


def words(value):
    # Mirrors shared/textUtils.js: Unicode letters/numbers, token length > 1.
    chunks = re.findall(r"[\w]+", normalize(value), re.UNICODE)
    return [chunk for chunk in chunks if len(chunk) > 1 and any(WORD_RE.match(c) for c in chunk)]


def tokenize(value):
    units = words(value)
    return units + [f"{a}_{b}" for a, b in zip(units, units[1:])]


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    csv.field_size_limit(sys.maxsize)
    nazario_path = DATA / "Nazario_5.csv"
    uci_path = DATA / "uci-sms" / "SMSSpamCollection"
    uci_texts = {
        normalize(line.split("\t", 1)[1])
        for line in uci_path.read_text(encoding="utf-8", errors="replace").splitlines()
        if "\t" in line
    }

    rows = []
    seen = set()
    overlaps = []
    with nazario_path.open(encoding="utf-8", errors="replace") as stream:
        for source_row, row in enumerate(csv.DictReader(stream), 2):
            # Match the extension's observable text path. Sender identity is
            # evaluated by a separate rule only when it is actually present.
            text = "\n".join(filter(None, [row.get("subject"), row.get("body"), row.get("urls")]))
            key = normalize(text)
            if not key or key in seen:
                continue
            seen.add(key)
            if key in uci_texts:
                overlaps.append({"row": source_row, "sha256": hashlib.sha256(key.encode()).hexdigest()})
                continue
            rows.append({"id": source_row, "label": "scam" if row["label"] == "1" else "safe", "text": text})

    rng = random.Random(SEED)
    selected = []
    for label in ("safe", "scam"):
        group = [row for row in rows if row["label"] == label]
        rng.shuffle(group)
        selected.extend(group[:1000])

    train, test = [], []
    for label in ("safe", "scam"):
        group = [row for row in selected if row["label"] == label]
        train.extend(group[:800])
        test.extend(group[800:1000])
    rng.shuffle(train)
    rng.shuffle(test)

    counters = {label: Counter() for label in ("safe", "scam")}
    docs = Counter()
    for row in train:
        docs[row["label"]] += 1
        counters[row["label"]].update(tokenize(row["text"]))

    vocabulary = set(counters["safe"]) | set(counters["scam"])
    safe_total = sum(counters["safe"].values())
    scam_total = sum(counters["scam"].values())
    vocab_size = max(len(vocabulary), 1)
    # Frequency pruning keeps common language evidence and avoids selecting only
    # rare, high-log-odds tokens. The deterministic tie-break makes the artifact
    # byte-for-byte reproducible.
    ranked = sorted(
        vocabulary,
        key=lambda token: (counters["safe"][token] + counters["scam"][token], token),
        reverse=True,
    )
    kept = set(ranked[:6000])
    compact = {
        label: {token: count for token, count in sorted(counters[label].items()) if token in kept}
        for label in ("safe", "scam")
    }
    model = {
        "schemaVersion": 2,
        "algorithm": "multinomial-naive-bayes",
        "labels": ["safe", "scam"],
        "seed": SEED,
        "docCounts": dict(docs),
        "totalDocs": len(train),
        "tokenCounts": compact,
        "totalTokens": {label: sum(compact[label].values()) for label in ("safe", "scam")},
        "vocabularySize": len(kept),
        "training": {
            "source": "Nazario_5.csv",
            "sourceSha256": sha256(nazario_path),
            "uciSha256": sha256(uci_path),
            "deduplicatedRows": len(rows),
            "removedExactUciOverlaps": overlaps,
            "selectedPerClass": 1000,
            "trainPerClass": 800,
            "testPerClass": 200,
            "split": "stratified-80-20",
        },
    }

    OUT.mkdir(parents=True, exist_ok=True)
    model_json = json.dumps(model, ensure_ascii=False, separators=(",", ":"))
    (OUT / "model.json").write_text(model_json + "\n", encoding="utf-8")
    (ROOT / "shared" / "modelData.js").write_text(
        "// Generated by research/train_v2.py; embedded for offline MV3 use.\n"
        f"export const MODEL_DATA = Object.freeze({model_json});\n",
        encoding="utf-8",
    )
    (OUT / "nazario_split.json").write_text(json.dumps({"train": train, "test": test}, ensure_ascii=False), encoding="utf-8")
    print(json.dumps({"modelBytes": len(model_json.encode()), "train": len(train), "test": len(test), "overlaps": len(overlaps)}))


if __name__ == "__main__":
    main()
