export const MAX_CONTENT_LENGTH = 5000;

export const CLASSIFICATION_THRESHOLDS = Object.freeze({
  suspicious: 35,
  scam: 70,
});

export const URL_SHORTENERS = new Set([
  "bit.ly",
  "tinyurl.com",
  "t.co",
  "goo.gl",
  "ow.ly",
  "is.gd",
  "buff.ly",
  "rebrand.ly",
  "shorturl.at",
]);

export const SUSPICIOUS_TLDS = new Set([
  "click",
  "top",
  "zip",
  "mov",
  "gq",
  "work",
  "support",
  "country",
  "stream",
  "monster",
  "fit",
]);

export const KEYWORD_GROUPS = Object.freeze({
  urgency: [
    "urgent",
    "immediately",
    "act now",
    "right now",
    "within 24 hours",
    "final warning",
    "expires today",
    "limited time",
    "asap",
    "now",
  ],
  fear: [
    "suspended",
    "locked",
    "frozen",
    "legal action",
    "lawsuit",
    "arrest",
    "compromised",
    "breach",
    "penalty",
    "terminated",
    "unauthorized login",
  ],
  authority: [
    "bank",
    "irs",
    "tax department",
    "police",
    "government",
    "microsoft support",
    "ceo",
    "hr department",
    "paypal",
    "amazon security",
    "delivery partner",
  ],
  secrecy: [
    "do not tell anyone",
    "keep this confidential",
    "secret",
    "private transaction",
    "between us",
    "do not involve anyone else",
  ],
  reward: [
    "lottery",
    "you won",
    "reward",
    "claim prize",
    "bonus payout",
    "free gift",
    "refund bonus",
    "cash prize",
  ],
  credentials: [
    "password",
    "passcode",
    "otp",
    "verification code",
    "2fa code",
    "security code",
    "login here",
    "confirm your account",
    "verify your identity",
  ],
  payments: [
    "gift card",
    "wire transfer",
    "crypto",
    "bitcoin",
    "wallet address",
    "bank transfer",
    "prepaid card",
    "send payment",
    "invoice overdue",
  ],
  remoteAccess: [
    "teamviewer",
    "anydesk",
    "remote desktop",
    "install this software",
    "screen share",
  ],
  malware: [
    "enable macros",
    "open attachment",
    ".exe",
    ".scr",
    ".iso",
    "download this file",
  ],
});

export const BEHAVIOR_SIGNALS = Object.freeze([
  {
    id: "urgency_pressure",
    label: "Urgency pressure",
    weight: 12,
    phrases: KEYWORD_GROUPS.urgency,
    reason: "The content pushes the user to act quickly before they can verify the request.",
  },
  {
    id: "fear_tactics",
    label: "Fear tactics",
    weight: 14,
    phrases: KEYWORD_GROUPS.fear,
    reason: "The content uses threats or negative consequences to pressure compliance.",
  },
  {
    id: "fake_authority",
    label: "Authority impersonation",
    weight: 12,
    phrases: KEYWORD_GROUPS.authority,
    reason: "The content invokes an authority figure or institution to appear legitimate.",
  },
  {
    id: "secrecy_pressure",
    label: "Secrecy pressure",
    weight: 10,
    phrases: KEYWORD_GROUPS.secrecy,
    reason: "The sender discourages normal verification or outside review.",
  },
  {
    id: "reward_bait",
    label: "Reward bait",
    weight: 10,
    phrases: KEYWORD_GROUPS.reward,
    reason: "The content uses prizes, rewards, or windfalls to lure the user.",
  },
  {
    id: "credential_harvest",
    label: "Credential harvesting",
    weight: 18,
    phrases: KEYWORD_GROUPS.credentials,
    reason: "The message seeks credentials or verification secrets commonly targeted in phishing.",
  },
  {
    id: "payment_pressure",
    label: "Payment pressure",
    weight: 16,
    phrases: KEYWORD_GROUPS.payments,
    reason: "The sender tries to redirect money into hard-to-recover payment channels.",
  },
]);